[colors.primary]
background = '#191114'
foreground = '#eedfe2'
 
[colors.cursor]
text = '#eedfe2'
cursor = '#d5c2c7' 
 
[colors.vi_mode_cursor]
text = '#191114'
cursor = '#ffb0cf' 
 
[colors.search.matches]
foreground = '#514348' 
background = '#f1bc97' 
 
[colors.search.focused_match]
foreground = '#514348' 
background = '#ffb0cf' 
 
[colors.footer_bar]
foreground = '#514348' 
background = '#eedfe2' 
 
[colors.hints.start]
foreground = '#514348' 
background = '#e1bdc9' 
 
[colors.hints.end]
foreground = '#514348' 
background = '#e1bdc9' 
 
[colors.selection]
text = '#191114'
background = '#ffb0cf'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#ffb0cf' 
yellow = '#8a4a66' 
blue = '#ffb0cf' 
magenta = '#f1bc97' 
cyan = '#e1bdc9' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
