[urgency_low]
timeout = 3
background = "#191114"
foreground = "#eedfe2"
highlight = "#6e334e"
fullscreen = delay
[urgency_normal]
timeout = 6
background = "#191114"
foreground = "#eedfe2"
highlight = "#6e334e"
fullscreen = delay
[urgency_critical]
timeout = 0
background = "#191114"
foreground = "#eedfe2"
highlight = "#ffb4ab"
fullscreen = show
