[urgency_low]
timeout = 3
background = "#191113"
foreground = "#efdee0"
highlight = "#713342"
fullscreen = delay
[urgency_normal]
timeout = 6
background = "#191113"
foreground = "#efdee0"
highlight = "#713342"
fullscreen = delay
[urgency_critical]
timeout = 0
background = "#191113"
foreground = "#efdee0"
highlight = "#ffb4ab"
fullscreen = show
