[urgency_low]
timeout = 3
background = "#111318"
foreground = "#e1e2e9"
highlight = "#204876"
fullscreen = delay
[urgency_normal]
timeout = 6
background = "#111318"
foreground = "#e1e2e9"
highlight = "#204876"
fullscreen = delay
[urgency_critical]
timeout = 0
background = "#111318"
foreground = "#e1e2e9"
highlight = "#ffb4ab"
fullscreen = show
