#!/usr/bin/env bash
#
# Launch a power menu
#
# Requires fzf and systemd (loginctl, systemctl)
#
# Author:  Jesse Mirabel <sejjymvm@gmail.com>
# Date:    August 19, 2025
# License: MIT

main() {
	local list=(
		"Lock"
		"Shutdown"
		"Reboot"
		"Logout"
		"Hibernate"
		"Suspend"
	)

	local options=(
		"--border=sharp"
		"--border-label= Power Menu "
		"--cycle"
		"--ghost=Search"
		"--height=~100%"
		"--highlight-line"
		"--info=inline-right"
		"--pointer="
		"--reverse"
	)

	local selected
	selected=$(printf "%s\n" "${list[@]}" | fzf "${options[@]}")


	case $selected in
		Lock)      hyprlock  ;;
		Shutdown)  systemctl poweroff ;;
		Reboot)    systemctl reboot ;;
        Logout)
        case "$XDG_CURRENT_DESKTOP" in
            niri)
                niri msg action quit
                ;;
            Hyprland)
                command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'
                ;;
            *)
                pkill -KILL -u "$USER"
                ;;
        esac
        ;;
        Hibernate) systemctl hibernate ;;
		Suspend)   systemctl suspend ;;
		*)         return 1 ;;
	esac
}

main
